# Generated by Django 4.2.29 on 2026-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
